### ISSUE TITLE
Archive action - wrong icon and dialogue text  #304

### ISSUE THREAD

**Issue by traveller66** [Team-Rocket2410/NotePad#7]
Archive action ­ wrong icon

and dialogue text #304

When in list view pressing the trash icon one gets "Are you sure you want to delete these item(s)?"although

the action is actually to archive the notes.

I guess this needs splitting out:

• "archive these item(s)" when in list mode, and also use a different icon

• "delete" when in achive mode
https://github.com/spacecowboy/NotePad/issues/304

**Comment by isprole** [comment]
can show

however i do not see where the archive mode is within the app
